### PR TITLE
Mediasoup bump to match the client version

### PR DESCRIPTION
**Pull request by keianhzo**
Bump the Mediasoup server side libs to match the once updated in the client https://github.com/mozilla/hubs/pull/3305

*Note: This PR shoul dbe merged a the same time as https://github.com/mozilla/hubs/pull/3305*

### CODE REVIEW

**Comment by vincentfretin** [comment]
Did you forget to merge?

**Comment by keianhzo** [comment]
Thanks @vincentfretin It will get merged with the next audio patch that's on its' way.

**Comment by vincentfretin** [comment]
You may want to update to latest version here and on hubs when you merge this. In this PR it's 3.6.24, we are now version 3.6.32
https://github.com/versatica/mediasoup/blob/v3/CHANGELOG.md

**Comment by keianhzo** [comment]
@vincentfretin Thanks, I've merged this in a later PR

**Comment by keianhzo** [comment]
Closing this in favor of https://github.com/mozilla/dialog/pull/12

**Pull request closed without merging**
